name: Deploy Test App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.39.1"

      - name: Install dependencies
        run: |
          cd test-app
          npm install

      - name: Build NPM package
        run: |
          rm -f deno.lock
          deno run --allow-read --allow-write --allow-env --allow-net --allow-run --no-lock _build_npm.ts

      - name: Build test app
        run: |
          cd test-app
          npm link ../npm
          npm run build

      - name: Copy index.html to 404.html
        run: cp test-app/dist/index.html test-app/dist/404.html

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./test-app/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
